### ISSUE TITLE
Bug on IE11

### ISSUE THREAD

**Issue by Mowso** [VodkaBears/Remodal#173] opened 2015-08-14 15:03 UTC
Hi, me again !

There might be a bug on Internet Explorer 11: when I try to close the modal it flashes before it disappears. Any suggestions?

**Comment by VodkaBears** [comment] 2015-08-17 14:17
Hi. I don't have yet.

**Comment by VodkaBears** [comment] 2015-09-13 19:18
Hard to reproduce constantly, so not critical.

**Comment by ImBobby** [comment] 2015-09-16 07:52
Just tried using BrowserStack Win8.1 IE11, could not reproduce. Screen recording will be very helpful to explain the issue.

**Comment by dancetrain** [comment] 2015-10-20 15:40
Have same issue
Here is screen recording: https://drive.google.com/file/d/0B0hWJ6WDxdFycnFSa2hMZV9HZlU/view

**Comment by iGoico91** [comment] 2015-10-29 16:15
Hi,

Sorry, but I'm still having this issue in IE 10 on my Windows Phone 8.

I have tried in my web app and in your home page, and in both case I can reproduce it.
If you want to reproduce it, you have to open the modal and sometimes if you close directly it's reopen the modal and then inmediately desappear.

I saw that it happens when the animation is not even started, and when the animation is started it open again and then it closed.

Thank you very much.

**Comment by ImBobby** [comment] 2015-10-30 01:24
I Tried testing it on windows phone 8.1 and I saw that flash. When a button close was clicked, the modal disappear, then quickly reappear then completely disappear. But it rarely happen, I tried opening and closing modal around 30 times and that problem only occur once.

It might be rendering issue but that's just a wild guess.

**Comment by iGoico91** [comment] 2015-10-30 10:13
Hi,

Finally I found that the problem occurs when it makes the animation of opening and closing, because in some case it no close correctly the modal in the closing state and then at the closed state it get close correctly.

So I remove the animation's styles in my css file and it looks that it works in IE 10.

```css
.remodal-is-opening {
	width: 0% !important;
	height: 0% !important;
	padding: 0 !important;
}

.remodal-is-closing {
	width: 0% !important;
	height: 0% !important;
	padding: 0 !important;
}
```

I hope that it helps, thank you.

**Comment by zacol** [comment] 2015-11-10 14:02
I have the same bug in IE10 and IE11.

**Comment by VodkaBears** [comment] 2015-11-29 21:37
9271ab5cad4012b40a335bcefa92ae47e3181453

**Closed** 2015-11-29 21:36 UTC
Labels: bug, help wanted
